global:
  postgresql:
    username: postgres
    # password: postgres
    existingSecret: psql-secret
  # storageClass: psql-manual

service:
  type: LoadBalancer
  ports:
    postgresql: 5433

postgresql:
  replicaCount: 2
  username: postgres
  # password: postgres
  existingSecret: psql-secret

pgpool:
  # adminPassword: postgres
  existingSecret: psql-secret


# comment out below to use default pv

# persistence:
#   existingClaim: postgres-volume-claim
#   storageClass: manual

# volumePermissions:
#   enabled: true

# comment out below to use custom pv

persistence:
  selector: 
    matchLabels:
      app: postgres-app
  storageClass: psql-manual

volumePermissions:
  enabled: true