apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-0
  # name: data-datasaku-postgres-postgresql-ha-postgresql-0
  labels:
    app: postgres-app
spec:
  storageClassName: psql-manual
  claimRef:
    name: data-datasaku-postgres-postgresql-ha-postgresql-0
    namespace: psql-dev
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-1
  # name: data-datasaku-postgres-postgresql-ha-postgresql-1
  labels:
    app: postgres-app
spec:
  storageClassName: psql-manual
  claimRef:
    name: data-datasaku-postgres-postgresql-ha-postgresql-1
    namespace: psql-dev
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres1