# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: minio-manual
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-0
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  claimRef:
    name: data-datasaku-minio-0
    namespace: minio-dev
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/minio/minio0
  # nfs:
  #   # The address 192.168.99.1 is the Minikube gateway to the host. This way
  #   # not the container IP will be visible by the NFS server on the host machine,
  #   # but the IP address of the `minikube ip` command. You will need to
  #   # grant access to the `minikube ip` IP address.
  #   server: 192.168.49.1
  #   path: '/Users/rhyando/code/development/_data/minio/minio0'
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-1
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  claimRef:
    name: data-datasaku-minio-1
    namespace: minio-dev
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/minio/minio1
  # nfs:
  #   # The address 192.168.99.1 is the Minikube gateway to the host. This way
  #   # not the container IP will be visible by the NFS server on the host machine,
  #   # but the IP address of the `minikube ip` command. You will need to
  #   # grant access to the `minikube ip` IP address.
  #   server: 192.168.49.1
  #   path: '/Users/rhyando/code/development/_data/minio/minio1'
